### ISSUE TITLE
[Question]  Connected React Router 라이브러리 설치해도 될까요?

### ISSUE THREAD

**Issue by parkharoi** [seunghoonKang/we-all-lie-fe#2]
### Connected React Router 라이브러리 설명

리덕스에서 주소를 변경 및 확인하기 위해 history객체를 관리하며 필요에 의해 꺼내쓸 수 있는 유용한 라이브러리

> 단방향 흐름을 통해 리덕스에서 router상태를 동기화 할 수 있다. (history객체 -> store-> router-> component)

> react Router 버전 v4, v5를 지원한다. 

> 함수형 컴포넌트를 지원한다. 

> redux-thunk나 redux-saga를 통해 히스토리 객체를 디스패치할 수 있다. 

**제가 지금 작성하는 로그인 페이지에서 히스토리 객체를 사용하면 아주 편리할거 같아서 여쭤봅니다!
다른 분들도 사용하시면 컴포넌트 별로 페이지 사용하실 수 있어서 편하실 겁니다 ! 
자세한 사용법은 아래 첨부하겠습니다.
확인해보시고 말씀해 주세요 ~**

https://hokeydokey.tistory.com/74

**Comment by yoooooooung** [comment]
안됩니다.

**Comment by parkharoi** [comment]
단호행 ㅠ

**Comment by yoooooooung** [comment]
조금 더 간절해보세요

**Comment by seunghoonKang** [comment]
좋아요 ! 사용하는건 읽어보겠습니다 👍

**Comment by parkharoi** [comment]
라이브러리 설치는 아래 코드 복붙 하시면 됩니다 !
yarn add connected-react-router

**Comment by parkharoi** [comment]
현재 이 라이브러리를 사용하지 않아요 충분히 구현할 수 있다는 생각이 들어 라이브러리 삭제를 했습니다!
