### ISSUE TITLE
[Share] 11/26 멘토링 로그인 토큰관리 질문 답변

### ISSUE THREAD

**Issue by parkharoi** [seunghoonKang/we-all-lie-fe#58]
# 정보 공유
11/26 멘토링에서 토큰 관리를 어떻게 하는지 질문을 받았고 어떻게 해야 가장 보안적으로 좋은지를 알아봤습니다.
아직 저희는 회원정보에 대한 중요한 내용을 담고 있지는 않지만 프로젝트가 딥하게 들어가게 된다면 써먹어도 좋을거 같습니다.

## 쿠키

`저장공간 (4KB)`

백엔드에서 로그인이 성공되면 access token을 http header에 넣어 로그인에 대한 응답을 보내고, 브라우저에서는 이 응답 헤더에 존재하는 쿠키를 브라우저에 저장하여 사용 

쿠키를 사용할 때에도 보안 이슈가 있다. CSRF로 해킹이 가능한데, 이는 이용자의 쿠키값이 요청에 반용되는 것을 이용해서 특정 사이트로 가장한 유사 사이트에 접속을 유도하고, 쿠키값이 반영되어 있는 상태로 개인정보를 유출하게 하는 특정 요청을 보내게  된다.

Same-site정책으로 커버가 가능한데 아직 완전한 상태는 아니다. 그래도 로컬/세션스토리지에 저장하는 것보다는 보안성이 좀더 높다고 할 수 있다.
(HttpOnly 설정을 추가한다면 클라이언트의 접근을 완전히 차단해서 해커가 자바스크립트 코드를 통해 정보를 탈취하는 것을 방지할 수도 있다.)
만료 시점을 기준으로 크게 두 가지로 나뉜다.
브라우저가 종료되면 삭제되는 session cookies와 지정된 만료일에 삭제되는 persistent cookies가 있다.

## 세션 스토리지

`저장공간 (5~10MB)`

세션 스토리지는 session cookies와 비슷하다. 
말 그대로 세션을 위한 저장 공간이며 세션이 종료되면 모두 삭제된다. 쿠키와 다르게 서버에서 접근할 수 없기 때문에 클라이언트에서 스토리지의 값을 꺼내서 서버에 전달해주어야 한다.

## 로컬 스토리지

`저장공간 (5MB)`

로컬 스토리지는 persistent cookies와 비슷하다. 근데 쿠키는 만료기간이 지나면 삭제되지만 로컬 스토리지에 있는 데이터는 반 영구적으로 저장이 가능하다. 
세션 스토리지와 마찬가지로 서버에서 접근할 수 없기 때문에 클라이언트에서 스토리지의 값을 꺼내서 서버에 전달해 주어야 한다.

# 결론
솔직히 보안이 크게 중요하지 않으면 로컬도 나쁘지 않은 거 같다. 반영구적이기도 하고, 다른 곳에 비해 많은 저장공간도 있기 때문이다.
하지만 보안에 신경을 써야 한다면 웹 스토리지(로컬 스토리지 + 세션 스토리지)는 좋지 못하다.
웹 스토리지에 저장된 값은 javascript 코드를 통해 언제든지 접근할 수 있는데 이는 웹 사이트에 악의적인 스크립트를 넣어 의도하지 않은 동작을 발생시키는 xss (cross-site scripting) 공격에 취약하다.
반면 쿠키는 앞에서 말했던 HttpOnly 속성을 통해 javascript를 통한 접근을 막을 수 있기 때문에 보안적인 측면은 쿠키가 더 나아 보인다.

**Comment by seunghoonKang** [comment]
정리가 매우 깔끔하네요 👍
