### ISSUE TITLE
[BUG] 빈자리 확인

### ISSUE THREAD

**Issue by parkharoi** [seunghoonKang/we-all-lie-fe#72]
### 버그 한 줄 설명
명확하고 간결하게 작성해주세요!

### 설명
기본값으로 빈자리가 있는걸 확인해야 하는데 for문을 돌고나면 빈자리로 string이 나오는게 아니라 undefined로 값이 확인된다.

  ```
const userCameras = [
    { nickName: '빈자리' },
    { nickName: '빈자리' },
    { nickName: '빈자리' },
    { nickName: '빈자리' },
    { nickName: '빈자리' },
    { nickName: '빈자리' },
    { nickName: '빈자리' },
    { nickName: '빈자리' },
  ];

  const ha = () => {
    for (let step = 0; step < 8; step++) {
      if (userCameras[step].nickName === '빈자리') {
        userCameras[step].nickName = userNickname[step];
      }
    }
    return;
  };
  ha();

```
### 스크린샷 또는 코드

<img width="1489" alt="스크린샷 2022-12-03 오후 7 28 11" src="https://user-images.githubusercontent.com/113865640/205436433-5d58a826-b571-44eb-8efc-807169d04a32.png">

**Comment by parkharoi** [comment]
생각보다 undefined 문제는 간단했다. 
내가 값이 안떠서 지운 return이 없다는것 !

> 이 현상을 이해하기 위해서는
> 원래 자바스크립트 함수에서 function(){}의 {}부분에는 return값을 따로 적지 않는다면return undefined;가 기본적으로 생략되어 있다는 것을 알아야 한다.
>  console.log는 마지막 값까지 모두 반환하는 특징을 가지고 있다.
> 그래서 console에 찍을값은 없지만 일단 결과를 반환해야하니까 생략되어 있던 return undefined;를 반환하는 것이다.
> 

### 방안 : return을 넣어서 해결하는 방안을 생각해 봐야겠다.

**Comment by tastekim** [comment]
`usersCameras[step].nickname = usersCameras[step]` 이면 저 nickname이라는 key에다가 `{nickname: "빈자리"}` 라는 객체를 value로 넣어서 그런거는 아닐까요,,?! 
그나저나 안녕하세요

**Comment by parkharoi** [comment]
안녕하세요 ~
덕분에 코드 간소화가 되었습니다 !
아까 위에 말한 이론으로 `return`을 요리조리 집어넣었는데 정작 `return userCameras;`를 안집어 넣어서 그런거였다...
(진짜 넣고 실행되자말자 기립박수 쳤다)

```
변경사항 : 
  let userCameras = [
    '빈자리',
    '빈자리',
    '빈자리',
    '빈자리',
    '빈자리',
    '빈자리',
    '빈자리',
    '빈자리',
  ];

  //입장하는 유저들
  const ha = () => {
    for (let step = 0; step < userNickname.length; step++) {
      if (userCameras[step] === '빈자리') {
        userCameras[step] = userNickname[step];
      }
    }
    return userCameras;
  };
  ha();

```

결과 : 
<img width="1442" alt="스크린샷 2022-12-03 오후 10 12 18" src="https://user-images.githubusercontent.com/113865640/205442600-ebe672a2-7e89-4eda-ae7f-16db99632326.png">
