### ISSUE TITLE
[BUG] svg 원하는 이미지가 불러오지 않는 오류 (해결)

### ISSUE THREAD

**Issue by seunghoonKang** [seunghoonKang/we-all-lie-fe#96]
## 버그 한 줄 설명
필요한 svg 파일을 import 하였는데 엉뚱한 이미지가 화면에 출력됨

## 설명
고양이 이미지를 출력하려 했는데, 엉뚱한 이미지가 출력되었습니다..
기존 svg를 쓸 때처럼 똑같이 import를 했는데 말이죠.
```js
import { ReactComponent as Preparing } from '../assets/prepared_cat.svg';
```
**원하는 형태**
![image](https://user-images.githubusercontent.com/59612529/206186695-12a4b7b5-39e4-4c58-8ca8-7e0dd83ce876.png)

**오류**
![스크린샷 2022-12-07 오후 9 30 34](https://user-images.githubusercontent.com/59612529/206186602-42e0b0de-182d-437f-853e-bdbc2705a993.png)

## 원인
다음의 오류는 단순하지만 꼭 확인해야 하는 오류였습니다.
모든 svg 파일의 다음 부분이 똑같이 적혀있어 발생하는 오류였습니다.
![image](https://user-images.githubusercontent.com/59612529/206187603-e95c54bf-b575-454f-9a56-b265d51dc146.png)

## 해결
**각 svg 파일에 고유한 id 값을 주었더니 해결되었습니다.**
![image](https://user-images.githubusercontent.com/59612529/206188094-1d3b587c-64c1-4fe0-9a0d-230052896507.png)

## 참고한 블로그
[리액트 SVG 파일 겹침 현상 | 여러개의 SVG 파일 사용시 이미지 겹침 현상](https://hello-yeond.tistory.com/m/156)

**Comment by parkharoi** [comment]
확인했습니다.
